export const FETCH_IMGS_START = 'FETCH_IMGS_ERROR';
export const FETCH_IMGS_SUCCESS = 'FETCH_IMGS_SUCCESS';
export const FETCH_IMGS_ERROR = 'FETCH_IMGS_ERROR';
export const FETCH_IMG_URL_SUCCESS = 'FETCH_IMG_URL_SUCCESS';